---
title: "CodeBook"
author: "xiayan"
date: "2024-02-28"
output: html_document
---


## R Markdown

###Dataset Overview
The Human Activity Recognition Using Smartphones dataset contains experiments carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. The embedded accelerometer and gyroscope captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz.

###Data Collection
The dataset was divided into two sets:

The training set (70% of the volunteers)
The test set (30% of the volunteers)
For each record in the dataset, the following information is provided:

Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration
Triaxial Angular velocity from the gyroscope
A 561-feature vector with time and frequency domain variables
The activity label
An identifier of the subject who carried out the experiment
###Files Description
features_info.txt: Shows information about the variables used on the feature vector.
features.txt: List of all features.
activity_labels.txt: Links the class labels with their activity name.
train/X_train.txt: Training set.
train/y_train.txt: Training labels.
test/X_test.txt: Test set.
test/y_test.txt: Test labels.
###Variables Description
The dataset includes the following variables:

subject: The ID of the test subject
activity: The type of activity performed when the corresponding measurements were taken
features: 561 features derived from the accelerometer and gyroscope measurements
###Activity Labels
The activity labels are as follows:

1.WALKING
2.WALKING_UPSTAIRS
3.WALKING_DOWNSTAIRS
4.SITTING
5.STANDING
6.LAYING
###Data Transformation
The raw data sets are processed with run_analysis.R script to create a tidy data set with the average of each variable for each activity and each subject.

###Steps of data transformation:
Merge the training and the test sets to create one data set.
Extract only the measurements on the mean and standard deviation for each measurement.
Use descriptive activity names to name the activities in the data set.
Appropriately label the data set with descriptive variable names.
From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
###Final Output
The final tidy dataset includes the following columns:

Subject: The ID of the test subject
Activity: The type of activity performed
Plus averages of each of the extracted features for each subject and each activity.
The tidy dataset is stored in tidy_data.txt.
